### ISSUE TITLE
Documentation update to latest project structure

### ISSUE THREAD

**Issue by attilaberencsi** [SAP-samples/btp-cf-cap-multitenant-susaas#10]
Hello here on this great repository,

I'd like to ask You to update the documentation to the latest project structure. This topic is complex enough and would be support understanding the basic components and their responsibilities of the solution in the first steps :):

https://github.com/SAP-samples/btp-cf-cap-multitenant-susaas/blob/main/docu/2-basic/1-understand-repo-structure/README.md

Some folder do not exists anymore, the hierarchy, structure and names changed etc., especially in the `app` folder. 

**Current documentation**

![image](https://user-images.githubusercontent.com/20442467/214577011-8684e29a-0ae4-4c18-b84e-6a6fb37ef014.png)

**Project**

![image](https://user-images.githubusercontent.com/20442467/214576401-6565edc9-141d-4971-969c-f40c83ef0016.png)

Thank You

Kind regards
Attila

**Comment by martinfrick** [comment]
Hi Attila, 

thanks for your input! This is highly appreciated! We will make ensure to update the documentation in the upcoming days! 

Greetings
Martin

**Comment by martinfrick** [comment]
The respective parts of the documentation have been updated accordingly. Thanks for your input!
