### ISSUE TITLE
What is the saas provisioning dependency to the html5Runtime.uaa.xsappname used for?

### ISSUE THREAD

**Issue by piejanssens** [SAP-samples/btp-cf-cap-multitenant-susaas#14]
[        dependencies.push({ xsappname: services.html5Runtime.uaa.xsappname });](https://github.com/SAP-samples/btp-cf-cap-multitenant-susaas/blob/basic/srv/provisioning.js#L91)

**Comment by martinfrick** [comment]
Hi @piejanssens, thanks for creating this issue. We will refactor this callback and remove the respective line. It should not be required in this place!

**Comment by alperdedeoglu** [comment]
Hi @piejanssens, @martinfrick 
In older @sap/approuter versions it was required to return HTML5 Repository Runtime as a dependency to be able to have a token exchanges with relevant subdomains of the incoming tenant. 

I agree with @martinfrick, now with newer versions, as far as I see from the source code this is not a **must have** anymore.

Thanks for contribution

**Comment by piejanssens** [comment]
Thanks @martinfrick @alperdedeoglu 

I'm having a hard time understanding how these dependencies are being used (to know which dependencies I might need to provide). I wish it was documented a bit more elaborate.

Is it correct to say that these are all service dependencies required for the individual subscriber tenants who are accessing the provider's @sap/approuter?

**Comment by alperdedeoglu** [comment]
In this context, dependency means, a service in provider subaccount, will be consumed by tenants subscribed to that multitenant application. Let us say if you return event-mesh as a dependency, this tells your event-mesh service to get this tenant information and allow to use the service from provider account. In HTML5 Repo Runtime context, as far as I see this is not required anymore. 

Dependencies are not directly related with @sap/approuter, but the SAP Business Technology platform itself.

**Comment by alperdedeoglu** [comment]
Hi Pieter,
In this context, We have come to a conclusion that HTML5 Repo runtime is required as a dependency to inform the HTML5 Repo Runtime service. Any incoming tenant should be delegated also to the dependent services with this dependency callback therefore the backing services are also informed about the incoming tenant.

BR,
Alper
