### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by attilaberencsi** [SAP-samples/btp-cf-cap-multitenant-susaas#19]
Dear SuSaas Team,

can You please confirm and update the [docu ](https://github.com/SAP-samples/btp-cf-cap-multitenant-susaas/blob/main/docu/4-expert/local-hybrid-development/README.md) if You also think, that testing WebApplications in step 2.1 is not possible, just in step 2.2 ?

So the green part of the docu should go to from 2.1 to 2.2. 

![image](https://user-images.githubusercontent.com/20442467/224497473-b9a680af-f65f-4215-907a-8b6a40ddd253.png)

Until the default-env.json.sample is not renamed to default-env.json 

![image](https://user-images.githubusercontent.com/20442467/224497910-549878a5-ef55-4361-b917-a298a007f9c2.png)

the ui5 resources cannot be served when executing **npm run start:local** in the app/approuter folder
![image](https://user-images.githubusercontent.com/20442467/224497961-78f574b2-ea97-480e-8440-496e63ba5a5e.png)

Thank You

Best regards, Attila

**Comment by martinfrick** [comment]
Hi @attilaberencsi,

feel free to check out the latest code and docs updates concerning this topic. I have faith that https://github.com/SAP-samples/btp-cf-cap-multitenant-susaas/commit/e4550da8e75e65e9c7e67a1fac54fe2040a6f82d will also tackle this issue! 

Thanks!
@alperdedeoglu and @martinfrick

**Comment by attilaberencsi** [comment]
Thank You!
