### ISSUE TITLE
VSCode - Hybrid Development - UI5 Version 1.111.1 Failure

### ISSUE THREAD

**Issue by attilaberencsi** [SAP-samples/btp-cf-cap-multitenant-susaas#21]
Dear SuSaaS Team,

following step 2.5 in the [hybrid development guide](https://github.com/SAP-samples/btp-cf-cap-multitenant-susaas/blob/main/docu/4-expert/local-hybrid-development/README.md) we're facing the following issue.

![image](https://user-images.githubusercontent.com/20442467/224507877-c19abe42-74dd-43ad-94bf-e28ecdf25560.png)

![image](https://user-images.githubusercontent.com/20442467/224507883-3c800923-63f4-4561-a606-754a05ea590c.png)

This issue happens on UI5 version 1.111.1.

After rebooting the application with the help of UI5 Diagnostics with version 1.108.10 the application loads as expected

![image](https://user-images.githubusercontent.com/20442467/224507937-3da6f4c0-c343-48ba-ae7f-912fe9e8f4c8.png)

![image](https://user-images.githubusercontent.com/20442467/224508032-33826e8c-16d1-4214-9dd6-65d64fba978c.png)

![image](https://user-images.githubusercontent.com/20442467/224508041-40dcb966-4ba2-4756-95a0-bf80930cf26e.png)

I did a trick in default-env.json (I saw it at another place).

![image](https://user-images.githubusercontent.com/20442467/224508070-467b33fc-2c97-41d8-b366-6eef124432fe.png)

This resulted to load the application with lower version by default and fixed the issue.

Can we fix this somehow in the GitHub repository as well ? I am not sure this is the best approach to push such, but works.

Thank you in advance

Best regards

Attila

**Comment by martinfrick** [comment]
Hi @attilaberencsi,

we appreciate your input and support on keeping the repository up-to-date! I will double-check on this issue tomorrow morning and update the default-env.json accordingly! As you probably noticed, the ui5 destination in the destination service configuration (mta.yaml) is already fixed on 1.108.4. 

Thanks again! 
Martin

**Comment by martinfrick** [comment]
Hi @attilaberencsi,

I have recently committed some code and documentation changes. As part of these changes, the version of SAPUI5 is now consistently fixed at 1.108.4, which we used for our testing purposes. Additionally, the UI modules and Application Router now include a local.html file, enabling easy local testing by running **cds watch**. With these files, there is no need for a ui5 destination as the resource path is fixed. Please feel free to test the changes and provide us with your feedback. We appreciate your efforts and encourage you to keep up the good work!

@alperdedeoglu and @martinfrick

**Comment by martinfrick** [comment]
Changes can be found in in the following commits (same applies to basic version)

https://github.com/SAP-samples/btp-cf-cap-multitenant-susaas/commit/e4550da8e75e65e9c7e67a1fac54fe2040a6f82d https://github.com/SAP-samples/btp-cf-cap-multitenant-susaas/commit/bcb7037e4812cb199c2c938a88c1d392076ff18b https://github.com/SAP-samples/btp-cf-cap-multitenant-susaas/commit/bcb7037e4812cb199c2c938a88c1d392076ff18b

**Comment by attilaberencsi** [comment]
Thank You Guys again!
This is the most valuable repository for me so far :) !
