### ISSUE TITLE
TypeError: this.options.selectionStrategy is not a function  

### ISSUE THREAD

**Issue by attilaberencsi** [SAP-samples/btp-cf-cap-multitenant-susaas#23]
Hello SuSaaS Team,

I followed the [troubleshooting section](https://github.com/SAP-samples/btp-cf-cap-multitenant-susaas/blob/main/docu/4-expert/troubleshooting/README.mdl) for subscriber destination resolution, but no luck.

I am getting an issue when accessing an S/4HANA onPremise destination maintained in the subscriber subaccount to fetch data from subscribers system via OData. 

![image](https://user-images.githubusercontent.com/20442467/224940854-9e011107-9d82-417f-b64b-267e38d1edc3.png)

`TypeError: this.options.selectionStrategy is not a function  at DestinationFromServiceRetriever.getSubscriberDestinationService `

![image](https://user-images.githubusercontent.com/20442467/224936919-2bc8ded7-17f6-4df2-9174-4860a6ad2f8f.png)

I've applied additions like adding connectivity as dependency in `provisioning.js` , and Also added mtx dependencies in `server.js` according to this [Community thread](https://answers.sap.com/questions/13571670/documentation-deploy-saas-solutions-mtx-dependenci.html).

![image](https://user-images.githubusercontent.com/20442467/224937265-365716d9-852d-40c2-951c-b387cc98f05d.png)

I also added connectivity to mta.yaml

![image](https://user-images.githubusercontent.com/20442467/224942841-135ff8ff-e44c-4b46-a2a2-5a3ba0e71185.png)

And bound to the application router
![image](https://user-images.githubusercontent.com/20442467/224943530-753d6386-00a7-452e-b3a8-cf16a91f63e4.png)

Also extended cds.requires in package.json with 

![image](https://user-images.githubusercontent.com/20442467/224940128-db5dfe79-a191-4a5f-b6c5-b7f54ccd9baa.png)

I deployed it to CF after that I did a new subscription, but no luck unfortunately . I am getting the same issue.

I might missed some configuration maybe somewhere. Cloud foundry is not enabled in subscriber account, and only the destination is created there.

In non-SaaS application I was able to fetch data from S/4HANA on Premise systems, there is something specific what I sure missed to do, but was not able to spot out clearly.

I am not sure this is off topic here, due I found references to subscriber destination resolution in troubleshooting section only, but no other documentation in this repository which is about connecting subscribers onPremise system from the cloud. In case this is not related to this SuSaaS solution, we can close this Issue.

Thank You for Your many help already in the past!

Best regards

Attila

**Comment by martinfrick** [comment]
Hi @attilaberencsi,

may I ask why you've bound the connectivity service and destination service to the Application Router? Shouldn't the CAP Backend be the right place for that? 

Thanks 
Martin

**Comment by martinfrick** [comment]
If this doesn't get us any closer to a potential solution, we need to setup things on our side and give it a try. We haven't actively used a backend connection from a subscriber subaccount in our scenario yet, still we thought the details on selectionStrategies might be useful for other developers, that's why we added the input to the Troubleshooting section!

**Comment by attilaberencsi** [comment]
Hi Martin @martinfrick ,

thank You for Your quick response.

Actually I bound it to both AppRouter and CAP Service, like the destination service is bound to both of them. I was unsure so I bound it to both of them.

Now I removed binding from AppRouter, and just kept bound it to the CAP service only. It did not help. 
I also tried to increase below versions to latest in package.json, due the issue seemed coming from there. It also did not help.

    "@sap/cds": "^6.3.2",
    "@sap/cds-dk": "^6.3.2",
    "@sap/cds-mtxs": "^1.3.3",
    "@sap/xsenv": "^3",
    "@sap/xssec": "^3",

Thank You

**Comment by martinfrick** [comment]
@alperdedeoglu suggested to remove the "alwaysSubscriber" option, as it is the default anyway! 

https://cap.cloud.sap/docs/guides/using-services?q=alwaysSubscriber#destination-resolution

Can you give this another try please?

**Comment by attilaberencsi** [comment]
Hello Martin @martinfrick , hello Alper @alperdedeoglu ,

magic tricks always welcome. Thank You for Your support. It works using Your "hack" :).

Application launches properly with the Subscribers application URL on BTP.

Unfortunately hybrid testing is blocked in VSCode. As I see [there are workarounds](https://answers.sap.com/questions/13112914/sap-cf-capm-connectivity-service-doesnt-work-when.html) for that.
But as we can do hybrid development in BAS with the trick You [mentioned](https://github.com/SAP-samples/btp-cf-cap-multitenant-susaas/issues/17),  we can do the full development lifecycle in BAS. 

Thanks again!

Best regards
Attila
