### ISSUE TITLE
Subscription failed. 

### ISSUE THREAD

**Issue by ilhanburak** [SAP-samples/btp-cf-cap-multitenant-susaas#25]
Hello, 
I tried to follow basic scope in trial accounts but I get an error when I try to subscribe deployed application. 
The error in <space>-susaas-srv as follows. 

`
{
  "level": "error",
  "logger": "cds",
  "component_type": "application",
  "correlation_id": "b048537b-e0b4-44f5-4116-d85f1c83f4f9",
  "tenant_id": "sap-provisioning",
  "host": "d3920515trial-spance-dev-susaas-srv.cfapps.us10-001.hana.ondemand.com",
  "user_agent": "Java/11.0.19",
  "content_length": "983",
  "accept": "text/plain, application/json, application/*+json, */*",
  "authorization": "Bearer ***",
  "b3": "0fe1452c66a7609539f60e99fb6e1296-39f60e99fb6e1296",
  "content_type": "application/json",
  "sap_passport": "<removed>",
  "traceparent": "00-57339f2a70d6b65e99411c901256527a-0ce868afe6328c20-01",
  "tracestate": "5b7c6964-f3bef2ea@dt=fw4;d;511b99cd;56dd;25;0;0;136;e830;2h01;3h511b99cd;4h56dd;5h01",
  "x_b3_spanid": "39f60e99fb6e1296",
  "x_b3_traceid": "0fe1452c66a7609539f60e99fb6e1296",
  "x_cf_applicationid": "5140b746-be29-4a26-b7de-253c56b31844",
  "x_cf_instanceid": "778b8c24-80d6-486c-5492-cc29",
  "x_cf_instanceindex": "0",
  "x_correlationid": "b048537b-e0b4-44f5-4116-d85f1c83f4f9",
  "x_dynatrace": "FW4;-205589782;13;1360763341;22237;37;1534880100;310;e830;2h01;3h511b99cd;4h56dd;5h01",
  "x_forwarded_for": "52.202.170.155, 10.0.200.1",
  "x_forwarded_proto": "https",
  "x_request_start": "1684962859818",
  "x_scp_request_id": "3f23ad5a-84a8-42b9-9f52-1937c1e24c2f-646E7E29-26E55",
  "x_vcap_request_id": "ab41650f-563d-4701-5cf8-32f1ff4e5f36",
  "x_correlation_id": "b048537b-e0b4-44f5-4116-d85f1c83f4f9",
  "timestamp": "2023-05-24T21:14:30.372Z",
  "msg": "HDI deployment failed with exit code 1",
  "stacktrace": [
    "Error: HDI deployment failed with exit code 1",
    "at /home/vcap/app/node_modules/@sap/cds/bin/deploy/to-hana/hdiDeployUtil.js:124:35",
    "at ChildProcess.<anonymous> (/home/vcap/app/node_modules/@sap/hdi-deploy/library.js:102:14)",
    "at ChildProcess.emit (node:events:513:28)",
    "at maybeClose (node:internal/child_process:1091:16)",
    "at ChildProcess._handle.onexit (node:internal/child_process:302:5)",
    "at Process.callbackTrampoline (node:internal/async_hooks:130:17)"
  ],
  "layer": "cds",
  "tenant_subdomain": "sap-provisioning"
}
`
Complete log files of susaas-srv ->
[susaas-Spance_dev-2023-05-24 21_23_56.304+0000.txt](https://github.com/SAP-samples/btp-cf-cap-multitenant-susaas/files/11559311/susaas-Spance_dev-2023-05-24.21_23_56.304%2B0000.txt)

Could you please help me which step I miss ?
Regards.

**Comment by alperdedeoglu** [comment]
Hi @ilhanburak, 
Thanks for reaching out!
May I ask if your SAP HANA Cloud Trial instance is up and running? Can you double check that?

**Comment by ilhanburak** [comment]
Hello, 
Yes it's :) I also tried with different patch versions of hana db ?

**Comment by alperdedeoglu** [comment]
Hi,
I was able to successfully deploy & subscribe with my personal SAP BTP Free-Tier Global account.
I will try to explain what I did step-by-step. 

## Steps 
I made sure my *SAP Hana Cloud* instance is up and running.
Then I have executed the commands below.
```sh
$ git clone https://github.com/SAP-samples/btp-cf-cap-multitenant-susaas.git
$ cd btp-cf-cap-multitenant-susaas
$ git checkout basic
$ npm install
$ npm run init:broker
```
After that, I have pasted my hashed broker credential in [this file](https://github.com/SAP-samples/btp-cf-cap-multitenant-susaas/blob/basic/configs/deployment/free-tier.mtaext) as documented [here](https://github.com/SAP-samples/btp-cf-cap-multitenant-susaas/tree/main/docu/2-basic/3-build-deploy-saas-application#1-prepare-the-saas-application-for-deployment).
Then I have executed the commands below.
```sh
$ mbt build -e ./configs/deployment/free-tier.mtaext   
$ cf deploy mta_archives/susaas_0.0.1.mtar
```
After deployment is completed I have made the setup of my Credential Store as described [here.](https://github.com/SAP-samples/btp-cf-cap-multitenant-susaas/tree/main/docu/2-basic/3-build-deploy-saas-application#2-setup-the-credential-store)

Then I have made my subscription as documented [here](https://github.com/SAP-samples/btp-cf-cap-multitenant-susaas/tree/main/docu/2-basic/4-subscribe-consumer-subaccount).

### Please see the screenshot below. 
<img width="1212" alt="image" src="https://github.com/SAP-samples/btp-cf-cap-multitenant-susaas/assets/39748566/cef78fbe-84cd-482a-aef5-1cf83208fd16">

I will keep this issue open, and will try to reproduce your error in a Trial account. In the meantime can you try again with a fresh clone?

**Comment by ilhanburak** [comment]
Hello Alper,
I don't have Free-Tier Global account. That's why I couldn't try those steps. Maybe there are some limitations in trial account other than documented in tutorial ?

**Comment by alperdedeoglu** [comment]
Hi @ilhanburak,
I have tried also with trial account and worked again, can you please make sure that you did the steps I mentioned above?

<img width="1264" alt="Screenshot 2023-05-26 at 01 14 23" src="https://github.com/SAP-samples/btp-cf-cap-multitenant-susaas/assets/39748566/b1ae21c4-bafc-4496-8663-c70fa4b27e48">

**Comment by ilhanburak** [comment]
Hello Alper

When I tried with free-tier, I got following error 
as mentioned  [troubleshooting](https://github.com/SAP-samples/btp-cf-cap-multitenant-susaas/blob/main/docu/2-basic/10-troubleshooting/README.md),  

```
Creating service "dev-susaas-credstore" from MTA resource "susaas-credstore"...
Service operation failed: Controller operation failed: 404 Updating service "dev-susaas-alert-notification" failed: Not Found: Error creating service "dev-susaas-alert-notification" from offering "alert-notification" and plan "free": Service plan free not found. 
Service operation failed: Controller operation failed: 404 Updating service "dev-susaas-credstore" failed: Not Found: Error creating service "dev-susaas-credstore" from offering "credstore" and plan "free": Service plan free not found. 
```
So, I executed following steps. 
1. I created catalog IDs for sb.
```
npm run init:broker
```
2. 
Copied hashed credentials to <b>config/deployment/trial.mtaext</b> file
```
ID: susaas.trial
_schema-version: 3.2.0
version: 1.0.0
extends: susaas

modules:
  - name: susaas-api-sb
    properties:
      SBF_BROKER_CREDENTIALS_HASH:  >
        {
          "broker-user": "sha256:2poLCy/J*****************f84Lw="
        }

resources:
  - name: susaas-alert-notification
    parameters:
      service-plan: standard
  - name: susaas-credstore
    parameters:
      service-plan: trial

```


3.  I built the project with trial.mtaext file
```
mbt build -e ./configs/deployment/trial.mtaext
```
4. I setup credential store  

btp-admin-user with current user
<img width="324" alt="btp-admin-user" src="https://github.com/SAP-samples/btp-cf-cap-multitenant-susaas/assets/25001599/e06b7b24-c5b4-480d-b4cc-d96537742990">

susaas-broker-credentials with plaintext password from first step. 
<img width="318" alt="susaas-broker-credentials" src="https://github.com/SAP-samples/btp-cf-cap-multitenant-susaas/assets/25001599/24092b5b-595d-48de-873c-9d101d0498b4">

5. then subscribe with subaccount 
<img width="410" alt="tenant-info" src="https://github.com/SAP-samples/btp-cf-cap-multitenant-susaas/assets/25001599/6ca942d6-047e-4cef-bbae-1741a7cdf370">

I still got same error :(

**Comment by alperdedeoglu** [comment]
Hi @ilhanburak,

Free plan is something only available in free-tier accounts. Your error is saying that your trial account does not have that service plan, which makes sense.

I am pretty sure that you are trying to build with free-tier.mta.ext file, or deploying an old mta_archive which has some free-tier information in it.

Can you please retry with steps below and let me know?
## Steps
1. Do a fresh clone of the repository.
2. Checkout to the basic branch of the repository with command below.
```sh
$ git checkout basic
```
3. Install npm packages with the command below.
```sh
$ npm install 
```
4. Generate your broker credentials via running the command below.
```sh 
$ npm run init:broker
```
5. Copy your generated hashed password into the placeholder in **/configs/deployment/trial.mtaext** as described in documentation. ( As you have shown in your response, step 2.)
6. Generate your mta_archive via using the **trial** file with the command below. And make sure that it is successfully completed.
```sh
$ mbt build -e ./configs/deployment/trial.mtaext
```
7. Deploy your application to the cf with following command.
```sh
$ cf deploy mta_archives/*
```

Can you please try exactly the same steps in the order I have provided?

**Comment by ilhanburak** [comment]
Hello Alper,
I tried it from scratch more than 10 times. Still same error.  
Provider SubAccount Region : US East (VA)

My environments are below. 
NodeJs  : v16.20.0. 
Cloud MTA Build Tool version 1.2.23
cf version 7.6.0+d1110f2.2023-02-27

Mtar file is uploaded the link below.
[link](https://we.tl/t-B7G48wknVK)

**Comment by ilhanburak** [comment]
Hello Alper,
I was trying on local computer. But when I tried with BAS it was successfull. I will compare with my installed versions of programs with BAS. Currently I'm using lastest on my computer. 

Regards.

**Comment by martinfrick** [comment]
Hi @ilhanburak, 

Thank you for your patience. Based on your latest message, it appears that you have successfully deployed the application using the trial plans. Are you still encountering the described issue during tenant subscription? If so, we would greatly appreciate a more detailed investigation this week.

Please note that Germany is currently enjoying a long weekend, but we will be fully committed to addressing your concerns tomorrow. To me, the issue seems reminiscent of a problem I encountered last week, which required a re-deployment of the shared database model. Kindly inform us of your current status, and we will work together to ensure that you are brought up to speed.

Best regards,
Martin

**Comment by ilhanburak** [comment]
Hi Alper,
Yes I’ll try ASAP .
Regards.
ilhan Burak

**Comment by ilhanburak** [comment]
Hi Alper,
It worked now. Thanks. 
Regards.
