### ISSUE TITLE
Variant Management & Personalization

### ISSUE THREAD

**Issue by timostark** [SAP-samples/btp-cf-cap-multitenant-susaas#27]
Hi All,

I've noticed that you have deactivated the personalization and variant management - certainly because the sandbox fiori launchpad does not offer an "lrep" endpoint (from the on-prem world).
Do you know any solution for hosting a multi tenant application while still beeing able to use personalization?

Thanks!

**Comment by timostark** [comment]
@martinfrick thanks for your Response. To give you a little bit more context : we are currently evaluating how we want to embed Our saas solution.. I see the following options and i dont really like any of them :)

1. use the launchpad service of our customer - - >only possible via iframe integration which has a lot of disadvantages
2. Use a local sandbox launchpad - - >no full feature set of fiori is supported, as the supporting backend services are simply missing in the sandbox (variant management, flexibility service, key user extensibility..). As far as I see that us your presented solution. 
3. Use a custom developed launchpad. Has some nice advantages, but off the standard services of fiori are still not working. 
4. Use a launchpad module and the portal service. This might be possible (we will evaluate next week) but honestly seems like a waste of money. I have to pay a license fee per admin and user - not super high but still influences the costing of small apps with minor license fees.

What was your vision of how this app should be presented /delivered to the end user? With the sandbox portal?

Thanks!
Timo

**Comment by timostark** [comment]
Ps: regarding

`I haven't tried variant management in the mulitenancy context yet, so you might be lucky and it is supported `

The point is that variant management, flexibility and key user extensibility require backend services (on abap the lrep service). Therefore if there is no magic functionality in the app router (like e.g. The user API) it simply is impossible to work - at least as to my understanding..

**Comment by martinfrick** [comment]
Hi @timostark,

as also mentioned in other questions on the topic of Variant Management, you can find the sample coding and data model definition for independently setting up the required LRep Service right here:

[https://github.com/SAP-samples/hana-shine-xsa/blob/main/core-node/router/routes/lrep.js](https://github.com/SAP-samples/hana-shine-xsa/blob/main/core-node/router/routes/lrep.js)

[https://github.com/SAP-samples/hana-shine-xsa/blob/main/core-db/src/data/lrep.hdbcds](https://github.com/SAP-samples/hana-shine-xsa/blob/main/core-db/src/data/lrep.hdbcds)

Unfortunately, I haven't tried this in a multitenant context yet, but feel free to give it a try and let us know!

Best
Martin

**Comment by martinfrick** [comment]
Regarding the Launchpad questions - Unfortunately, I don't have any solid advice to offer at the moment. In the long run, we're expecting option 2 to become available, which would allow you to use multitenant SaaS apps in the subscriber subaccount launchpad. However, we don't have an official release date for that feature just yet.

In the meantime, you might want to take a look at a workaround and some extra feedback from our community experts. They've shared some details in the comments of this [blog post](https://blogs.sap.com/2023/02/14/what-you-should-know-about-sap-build-work-zone-standard-and-advanced-edition-formerly-known-as-sap-launchpad-service-and-sap-work-zone). While we can't guarantee that this approach will continue to work in the future, it did work for us a few months back.

It's a bummer, but for now, I think your best bet is to stick with the Sandbox Launchpad (or your own entry page implementation) and wait for the official release of the multitenant launchpad features for subscriber subaccounts. Keep an eye on the blogs and groups linked in the comments above for any updates.

**Comment by timostark** [comment]
@martinfrick  thank you very much for your response. The blog post comment is very interesting, but I will not "waste" time for that approach, as it all sounds very hacky / not production ready.
The lrep service implementation however is very helpful. The migration will be a little bit of effort (I will try to use standard rest implementation of CAP. In that case the multi-tenancy implementation should come out of the box).
I will comment in the next days if that solution works fine.

**Comment by alperdedeoglu** [comment]
Hi @timostark,
I am closing this one, please feel free to re-open this one once you have an idea or solution.
