### ISSUE TITLE
Login Screen in Subscriber subaccount

### ISSUE THREAD

**Issue by nwo-cw** [SAP-samples/btp-cf-cap-multitenant-susaas#28]
Hi experts, 

when I try to run the app from the subscriber subaccount, then I get redirected to an SAP HANA XS Advanced(https://authentication.us10.hana.ondemand.com/login) login screen instead of the Cloud Identity Service login screen. 

![image](https://github.com/SAP-samples/btp-cf-cap-multitenant-susaas/assets/118440008/f48b3eb9-3734-4ad2-93b5-f38968706368)

The routes got created automatically:

![image](https://github.com/SAP-samples/btp-cf-cap-multitenant-susaas/assets/118440008/152a0d61-0deb-4a00-b608-dba4b1f21f09)

I established trust to my Identity Authentication Tenant in the subaccount. I'm not sure what I did wrong, I also tried to redeploy and I created a another subscriber subaccount without success. Can you point me into right direction?

Thanks,

Nicolas

**Comment by martinfrick** [comment]
Dear @nwo-cw,

can you please provide us any contact details so we can reach out to you? Then we can have a check on it! In the meantime, can you kindly post your TENANT_HOST_PATTERN? Just to make sure there is no issue with that one... 

@alperdedeoglu & Martin

**Comment by nwo-cw** [comment]
Hi Martin, 
Thank you! I will send a mail with my contact details to your sap account.

TENANT_HOST_PATTERN: ^(.*)-susaas-Dev.cfapps.us10-001.hana.ondemand.com

Thanks,

Nicolas

**Comment by nwo-cw** [comment]
The issue was caused by a capital letter in the Cloud Foundry Space name. We changed it from "Dev" to "dev" and then it worked. Thank you @martinfrick @alperdedeoglu !!!

Thanks,

Nicolas
