### ISSUE TITLE
Missing parameter subaccountId for function registerBTPServiceBroker?

### ISSUE THREAD

**Issue by gregorwolf** [SAP-samples/btp-cf-cap-multitenant-susaas#29]
Hi @martinfrick and @alperdedeoglu,

I'm trying to understand more details how the Service Broker will appear in the marketplace of the consumer subaccounts that subscribed the multitenant app. I think this is triggered during subscription in [srv/utils/automator.js#L27](https://github.com/SAP-samples/btp-cf-cap-multitenant-susaas/blob/basic/srv/utils/automator.js#L27) by calling the [registerBTPServiceBroker function](https://github.com/SAP-samples/btp-cf-cap-multitenant-susaas/blob/basic/srv/utils/automator.js#L102). But to me it seems that the parameter subaccountId which is passed to the unregisterBTPServiceBroker function is missing here. That way there will not be a subaccount specific registration. Also the deletion will fail as the registration that is searched for does not exist.

Looking forward for your clarification.

Best Regards
Gregor

**Comment by martinfrick** [comment]
@gregorwolf - yepp that looks like a bug I agree! We will double-check tomorrow and provide an update! From what I remember, when it comes to the subaccount specific registration, the respective subaccount id will be attached automatically, to have unique service broker registration id (see Peripli docs - https://github.com/Peripli/specification/blob/master/api.md#registering-a-service-broker) . Still, the missing space name might cause an issue during delete phase - I agree!

**Comment by martinfrick** [comment]
Hi @gregorwolf,

I've pushed the respective [change](https://github.com/SAP-samples/btp-cf-cap-multitenant-susaas/commit/e71ca2bc621a0aa43d007a7ec5be5a5f114c353c) a few hours ago. Please let me know in case this doesn't solve your issue! In our environment, I took the opportunity to verify the successful registration and unregistration of the service broker!

Once again, we appreciate your valuable input and the support you've provided in ensuring the smooth operation of our sample scenario. Thank you!

@alperdedeoglu and @martinfrick

**Comment by gregorwolf** [comment]
Hi @martinfrick,

I think still an additional correction is needed in registerBTPServiceBroker(). Right now it is:

```
await this.serviceManager.createServiceBroker(`${process.env.brokerName}-${appEnv.app.space_name}`,
```

for the creation. But that doesn't match your updated deletion where you read the service broker in unregisterBTPServiceBroker(subaccountId) with:

```
this.serviceManager.getServiceBroker(`${process.env.brokerName}-${appEnv.app.space_name}-${subaccountId}`)
```

So either you add subaccountId as a parameter to registerBTPServiceBroker(subaccountId) and use:


```
await this.serviceManager.createServiceBroker(`${process.env.brokerName}-${appEnv.app.space_name}-${subaccountId}`,
```

for the creation or you remove subaccountId from unregisterBTPServiceBroker() and make it:

```
this.serviceManager.getServiceBroker(`${process.env.brokerName}-${appEnv.app.space_name}`)
```

CU
Gregor

**Comment by alperdedeoglu** [comment]
Hi @gregorwolf,
When you register a service broker, subaccountId is added as a postfix to your service broker name automatically by platform. (At least that was the case for us and also worked other stakeholders)
Therefore you only need  to be precise while unregistering your broker by name.

Best, 
Alper - Martin

**Comment by martinfrick** [comment]
Thanks for the additional details @alperdedeoglu - In my test environment things worked based on the latest changes!
