### ISSUE TITLE
SusaaS or SuSaaS?

### ISSUE THREAD

**Issue by gregorwolf** [SAP-samples/btp-cf-cap-multitenant-susaas#30]
Hello @alperdedeoglu and @martinfrick,

just a small thing: In the README.md you introduce Sustainable SaaS as SusaaS. But a bit later it's also mentioned as SuSaaS. Based on the long name Sustainable SaaS I would suggest SuSaaS at all places where currently SusaaS is used.

CU tomorrow
Gregor

**Comment by martinfrick** [comment]
Howdy @gregorwolf, 

We really appreciate your helpful input and valid feedback on the "convenience" aspects of our use-case! We'll definitely think about doing a Strg-H rebrand...! The only issue is that the SusaaS brand is already mentioned in a bunch of different places, which makes it a bit tricky. I love your idea though, so maybe we can revisit it when we merge the Kyma and Cloud Foundry repositories down the line. That way, we'll have a chance to revamp our blogs and other publications as well!

Thank you once again, and please don't hesitate to bring up any additional issues or concerns you may have. Your input is highly valued, and we welcome any further topics you'd like to discuss : ) 
@alperdedeoglu and @martinfrick
