### ISSUE TITLE
Availability of SAP Discovery Center mission?

### ISSUE THREAD

**Issue by gregorwolf** [SAP-samples/btp-cf-cap-multitenant-susaas#31]
Sorry for all the new issues :-). 

The README mentions that this project should be available in the [SAP Discovery Center](https://discovery-center.cloud.sap/) soon. I've tried different searches in the Mission Catalog:

- [multitenant](https://discovery-center.cloud.sap/protected/index.html#/missionssearch/multitenant/)
- [Sustainable](https://discovery-center.cloud.sap/protected/index.html#/missionssearch/Sustainable/)
- [saas](https://discovery-center.cloud.sap/protected/index.html#/missionssearch/saas/)

but wasn't able to find it. Is the publication still planned?

**Comment by alperdedeoglu** [comment]
Hi @gregorwolf, 
Thanks for reaching out.
We need to align on this internally.
Not if that is the first priority, given the current workload. 
I will align with my colleagues and come here again to update this issue.

**Comment by martinfrick** [comment]
I completely agree with Alper's comment, and I wanted to add a quick note. We are currently assessing the possibility of merging the Cloud Foundry repository with our Kyma repository. This consolidation would greatly streamline the maintenance of the corresponding Discovery Center mission and GitHub repository. However, please understand that our backlog is currently quite full, and we are prioritizing the most urgent updates first, as Alper mentioned. We appreciate your patience and understanding as we work through these tasks.

**Comment by gregorwolf** [comment]
To set priorities right I would value additions and improvements to the sample itself more than adding it to the Discovery Center. The benefit of the Discovery Center is just the additional visibility.
