### ISSUE TITLE
different git repository for every app to reduce development dependencies

### ISSUE THREAD

**Issue by poonambk** [SAP-samples/btp-cf-cap-multitenant-susaas#37]
Hi,

we have separate  git repository of our custom fiori apps. we want to include those app in susaas solution. 
can we keep separate repository for every app and refer/use them sussas launchpad config or app folder.

**Comment by martinfrick** [comment]
@poonambk - Can you please do us a favour and open this issue in our new repository? 
As explained in the main README, issues in this repository will no longer be answered.

https://github.com/SAP-samples/btp-cap-multitenant-saas
