### ISSUE TITLE
Wrong documentation

### ISSUE THREAD

**Issue by maxi1555** [SAP-samples/btp-cf-cap-multitenant-susaas#4]
[The documentation](https://github.com/SAP-samples/btp-cf-cap-multitenant-susaas/blob/be6c6b653075b67c128f50304405f239135148f5/docu/2-basic/10-troubleshooting/README.md) says "lite" service plan for "alert notification service", but in the [trial mta file](https://github.com/SAP-samples/btp-cf-cap-multitenant-susaas/blob/basic/configs/deployment/trial.mtaext) file you can find the correct service plan "standard"

**Comment by alperdedeoglu** [comment]
Hi @maxi1555,
Thank you for the contribution.
Relevant section has been updated.
