### ISSUE TITLE
Error when deploying susaas-db-com

### ISSUE THREAD

**Issue by nocin** [SAP-samples/btp-cf-cap-multitenant-susaas#5]
Hi,

I'm trying to follow the steps from [here](https://github.com/SAP-samples/btp-cf-cap-multitenant-susaas/tree/main/docu/2-basic/3-build-deploy-saas-application#1-prepare-the-saas-application-for-deployment), deploying the application in the BTP Trial using the BAS, but the deployment fails for the `susaas-db-com-dev` service with:

**ERR! network request to http://nginx-redirector.repo-cache.svc.cluster.local/repository/appstudio-npm-group/@sap/hdi-deploy/-/hdi-deploy-4.5.1.tgz failed, reason: getaddrinfo ENOTFOUND nginx-redirector.repo-cache.svc.cluster.local**

Full log: [susaas-db-com-dev-2022-11-14 14 06 33.329+0000.txt](https://github.com/SAP-samples/btp-cf-cap-multitenant-susaas/files/10003884/susaas-db-com-dev-2022-11-14.14.06.33.329%2B0000.txt)

When googling, I found this discussion in the SAP Community: https://answers.sap.com/questions/13588682/deploy-error-when-using-cap-and-hana-database.html
But I was expecting the sample to work out of the box, without doing any changes to the npm registry, deleting the package-lock.json or anything else. Can you confirm/recreate this issue on the trial landscape?

Thanks & KR
Nico

**Comment by alperdedeoglu** [comment]
Hi @nocin,
Thank you very much for your contribution.
Actually, we have included an **.npmrc** file in the root directory of the project, to be able to avoid the npm registry issue.

I have done the following:

1. Created a SAP BAS Subscription on Trial Account
2. Created a new space via choosing the full-stack development option
3. Cloned the repo and checked out to the basic branch
4. Run the commands and follow the steps from [here](https://github.com/SAP-samples/btp-cf-cap-multitenant-susaas/tree/main/docu/2-basic/3-build-deploy-saas-application#1-prepare-the-saas-application-for-deployment) as you mentioned 

At the end, the deployment was successful for me so unfortunately I can not reproduce your issue. Please 
see the screenshot below for the successful deployment and date.

Maybe you can share what have you done to overcome this issue on your end, then I can add the steps to the 
[relevant troubleshooting section](https://github.com/SAP-samples/btp-cf-cap-multitenant-susaas/tree/main/docu/2-basic/10-troubleshooting).

BR,
Alper

![trial-deployment](https://user-images.githubusercontent.com/39748566/201901538-64ff9ad3-0344-4080-8810-8819b88b8c9a.jpg)

**Comment by alperdedeoglu** [comment]
Hi @nocin,
I sincerely appreciate the time and effort you put into this.
Your efforts on behalf of the community are greatly valued.

I took a look at the discussions and the problem, as far as I understand, even though you have the .npmrc file in your root your package-lock.json file under your **gen/db-com** directory has local npm registry for SAP Business Application Studio.
Can you check if this is the case?
If so this seems to be a SAP BAS issue.

Let me know if the following steps are helpful.

1. Check SAP HANA Cloud Trial is running, if not please start it.
2. Undeploy the application using the command ```cf undeploy susaas --delete-services --delete-service-keys --delete-service-brokers```
3. Open directory _/home/users/_ in your SAP Business Application Studio. Find the **.npmrc** file under that directory and change the value as shown below. ![npm-registry-bas](https://user-images.githubusercontent.com/39748566/202028070-2ada4372-e234-44e7-8819-fef8cb252774.jpg)
4. Build the application again with the command ```mbt build -e ./configs/deployment/trial-private.mtaext````
5. Deploy the application with the command ```cf deploy mta_archives/susaas_0.0.1.mtar```

Kind Regards,

Alper

**Comment by nocin** [comment]
Hi @alperdedeoglu,

I followed your steps and replaced the registry entry from
![grafik](https://user-images.githubusercontent.com/35531968/202442269-b404905e-c674-4587-b8de-3ac39d07acac.png)
to
![grafik](https://user-images.githubusercontent.com/35531968/202450020-2e709410-056c-4e04-bebb-8013c8525c11.png)

Now the package-lock.json under gen/db-com has the correct npm registry after building. 

There was one last step I had to make. When trying to deploy the "susaas-db-com-dev" failed again. But this time there was another reason:

`#2.0#2022 11 17 12:31:58.460#Z#DEBUG#com.sap.cloud.lm.sl.xs2.604e2745-6673-11ed-a7b5-eeee0a9e8155.susaas-db-com-dev.executeTaskTask#
######org.cloudfoundry.multiapps.controller.persistence.services.ProcessLogger########flowable-async-job-executor-thread-1602###
[PollExecuteTaskStatusExecution] [susaas-db-com-dev] f9383bbc-4435-4144-bc58-80d2b7cc423a [Thu Nov 17 12:31:39 UTC 2022] Error: Connection failed (RTE:[89013] Socket closed by peer {10.128.205.130:41766 -> 34.202.189.140:443} (10.128.205.130:41766 -> adb7bc07-e190-419b-a98d-6468e201b38e.hana.trial-us10.hanacloud.ondemand.com:443)) (STDERR, APP/TASK/deploy)#
`

I could fix that by changing the HANA DB settings.
![grafik](https://user-images.githubusercontent.com/35531968/202449120-41666d04-8026-4c36-93a0-3a4b3821cb28.png)
But I'm a bit confused, why this is now necessary when deploying from BAS.

Anyway, finally the deploy process finished with success! :-)

After posting my previous answer, I also tried to deploy [this multitenancy sample](https://github.com/SAP-samples/cloud-cap-multitenancy) and got the same buildpack errors. This led me to the same conclusion that it must be a BAS problem. Alltough I'm wondering why nobody else had this problem yet.

Thanks so much for your help! Now that the application is deployed I can finally have a look in the actual example in the next days!

Thanks & Regards
Nico
